### PR TITLE
Refactor interpolation code

### PR DESCRIPTION
**Pull request by pavlin-policar**
For the past month or two, I've been playing around with this method, and in order to better understand how it works, I've rewritten most of the interpolation code, as it was quite confusing.

**Description of changes**

My primary goal here was to make the code understandable to anybody following your paper.

The first thing I did was run formatting on the project, as it really was quite inconsistent and that really bugs me :) Unfortunately, this makes the entire PR quite large, having touched every file in the project.

The files I did change and that should be reviewed are `nbodyfft` (I rewrote most of this) and `tsne` (I didn't really do much here, changed a few things in the parts that relate to the FFT bit.

I noticed that there was a lot of seemingly needless memory rearranging via `iarr`, `ysort` and the likes. After a bit of head scratching, I found that the code basically ensures that points belonging to the same box (or interval) are rearranged to be close to each other in memory. This really isn't necessary, because we can compute the correct interval index on the fly, saving on a lot of memory allocation and rearraging. I removed all of that code and comptued the indices on the fly. IMO this makes the function a whole lot clearer and understandable.

The indices are a bit complicated to compute e.g.

```
int idx = (box_i * n_interpolation_points + interp_i) * (n_boxes * n_interpolation_points) +
          (box_j * n_interpolation_points) + interp_j;
```

but if you think about it a bit, it is easier to get your head around than the previous rearranging. I just took a piece of paper and drew a grid to figure these out and it's really quite easy. This also has the added benefit of being a bit faster than the previous version, since we're not wasting time copying memory around.

Other than that I made the code more C++ish (under the guidance of intelliJ Clang-tidy warnings. I am by no means good at C++ so change things at will) and added comments that I thought would make the code clearer to somebody following your paper. I also removed a lot of commented out code that was presumably there for debugging, as it was taking up a lot of space and making everything very unreadable.

I also added a CMakeLists.txt as per the recommendation of intelliJ. I think that's really it, but as I have been working on this for a while, I may have forgotten to mention some small thing.

**End note**

I was fairly careful that the results I got were always still correct, but one can never be too careful. If you find any bugs or issues, I'll be sure to correct them.

Also, I'd ask you make sure that my comments are in fact correct, as understanding the code was my primary goal here and making it understandable for anybody going through it in the future. A misleading comment is worse than no comment at all. Same goes for variable names.

As requested, I rebased my branch on top of the latest master so you guys wouldn't have to deal with the many merge conflicts. I haven't had the chance to test the functionality you guys added in the past two months. It should work, but it should be tested.

### CODE REVIEW

**Comment by linqiaozhi** [comment]
@pavlin-policar , thank you so much for your hard work to improve the quality of the code base! It is much appreciated!

I will be going through your changes in detail, but one thing I wanted to ask about was the CMakeLists.txt. You mentioned you added it because intelliJ suggested it, but I'm a little worried that it complicates things for users. In particular, it requires users to have Cmake installed so that it can generate a makefile. For cross-platform projects with lots of dependencies that are difficult to link, it is worth it, but here the compilation is so simple that I do not think it is necessary.

Do you think you could remove the CmakeLists (and associated lines in the .gitignore)? Please let me know if I am perhaps missing the point of it...

**Comment by pavlin-policar** [comment]
Yes, you make a very good point. I am not familiar with C++ build systems, so I just assumed IntelliJ comes with good defaults. I have absolutely nothing against removing it.

**Comment by pavlin-policar** [comment]
I'm sorry this took so long, but I've removed it now. Have you had a chance to go over the code in detail? Does everything look alright? If so, I'll rebase one last time to get rid of these pesky merge conflicts.

**Comment by linqiaozhi** [comment]
Hey @pavlin-policar, thanks so much for following up. My apologies for taking so long to look at it in detail--these past two weeks have just been really crazy. I plan to review it this weekend--then you can go ahead and rebase and we can merge. 

Thanks again for following up--I will get back to you shortly!

**Comment by linqiaozhi** [comment]
Hey @pavlin-policar, I reviewed your updates, and they are excellent. Thank you for putting the time into improving the quality of the code base--I think it will be easier for people to figure out what is going on with the numerics now. 

I ran some [test code](https://github.com/linqiaozhi/cauchy-kernel-interpolation-accuracy) on your updated implementation of the nbodyfft, and it gives the same accuracy as before (e.g. with settings in that repo, 7-8 digits), and even seems a fair bit faster (as you suggested).

Just one quick question, you have a "TODO" here, 

https://github.com/pavlin-policar/FIt-SNE/blob/4479082130d5809862f5c9926b273d36267845dd/src/nbodyfft.cpp#L84-L88

and I was not too sure what it is referring to. Did you observe negative values in indices calculated in that line?

Other than that, please go ahead and rebase, PR, and I will happily merge!  Thanks so much!!

**Comment by pavlin-policar** [comment]
Thanks for verifying that this works @linqiaozhi!

I added the todo comment you mentioned to the existing code - this was there before I touched anything - because I did not understand why this check is necessary. I still don't - in my mind, a negative index should never occur here. I left it in because I was not sure if there's some edge case I don't know about. I'll remove this to avoid any sort of confusion.

I'll try to rebase this asap, but things are quite busy right now.

**Comment by dkobak** [comment]
Hi @pavlin-policar. Is this something you plan to do any time soon? I am working on several additions to the `tsne.cpp` (one PR currently pending, several others coming up soon), and your PR conflicts with them because of the formatting that you did. I am wondering what's the best way to proceed here so that everything is integrated smoothly.

I haven't been (and won't be) touching `nbodyfft`.

**Comment by dkobak** [comment]
@pavlin-policar Cool. So now there is this PR pending and also my yesterday's PR that adds some functionality to `tsne.cpp`,as discussed previously with George: https://github.com/KlugerLab/FIt-SNE/pull/25. As they probably conflict between each other, I'm not sure what will happen once of them gets merged. I am not very experienced in github. What would be the best way to proceed now?

I have some other things that I was going to refactor & implement into tsne.cpp, but I guess I should better wait now until these two PRs are incorporated...

**Comment by pavlin-policar** [comment]
I think it would be best to finally knock out the monstrosity that is this PR. I really shouldn't have run formatting on the project, but now it's so deeply embedded in the commits that there's really no going back, so best get that out of the way as soon as possible.

As for your PRs, you're going to have to run

```
git checkout master  # switch to master
git pull upstream master  # fetch the latest master branch
git checkout <your-branch>  # checkout your PR branch
```

then

```
git rebase master
```

Rebasing can be a pain, but if your code doesn't differ too much from my code, then it really shouldn't be too hard. In case you ever mess up in between you can run `git rebase --abort`.

My stategy for these commits where my changes are huge and the other commit's changes are small is to just take my file as the base, look at the diff of your commits, then add the differing lines, commit by commit. If you look at the thing that git produces for you, it can be very confusing. If you follow the commits one by one, and add each of the changes, then this should be fairly smooth, although tedious.

**Comment by linqiaozhi** [comment]
Hey @pavlin-policar and @dkobak, both of your PRs currently have no conflicts (thanks so much for rebasing again, Pavlin). What would be easier, for me to first merge Pavlin's PR and then Dmitry rebases to that, or vice versa? Dmitry's changes in #25 are much more minor (5 vs. 45 files changed, due to the formatting changes), so I'm not sure which one is easier for everyone. 

Please let me know your thoughts--and I agree, let's get these PRs done so won't have any more conflicts. 

Thank you for these excellent contributions.

**Comment by dkobak** [comment]
@linqiaozhi: I have little experience in this so I think @pavlin-policar is in a better position to say what is the best course of action now. As I understood him, he suggests that his PR is merged first. I'd be only happy if mine is merged first because then I don't need to do anything else here, but if it's easier the other way round, then I will do my best with rebasing asap after this PR is merged.

@pavlin-policar Please confirm.

**Comment by pavlin-policar** [comment]
@dkobak You're right. But having looked over your PR in question, I see that it would be fairly easy for me to rebase my changes on top of yours, so maybe that's the best course of action. That way, @dkobak, you don't have to worry about rebasing.

@linqiaozhi so I suggest that @dkobak's PR is merged first, then I'll rebase mine on top of that, then that can be merged.

**Comment by linqiaozhi** [comment]
@pavlin-policar sounds good to me! I'll go ahead and merge #25 as soon as possible; looks like there might be one tiny bug to fix before it is good to go.

**Comment by linqiaozhi** [comment]
@pavlin-policar, #25 is now merged! Sorry for the additional work of rebasing again--when you are done, I will merge it right away, so there will be no more conflicts.

Thanks again.

**Comment by pavlin-policar** [comment]
>  I see that it would be fairly easy for me to rebase my changes on top of yours

Famous last words. This was actually fairly tricky, and I hope everything still works. I've compiled it and ran a minimal example in R, but I haven't tested anything else, and I don't think I'll have the time to do so anytime soon. In case anything is broken I suggest just fixing it on top of this so we can finally be done with this.

Please test this to verify that the embedding is still correct (it should be) because that's the only thing I did actually change, the rest of my changes are just formatting and renaming variables to slightly more informative names.

**Comment by dkobak** [comment]
@pavlin-policar I pulled `pavlin-policar:refactor-interpolation`, ran it on MNIST via Python, and tested the load/save feature that I added in the last PR. Everything seems to work fine. So it looks like @linqiaozhi can go ahead with merge. If it gets merged over the weekend, I will be working on some further PRs and will be able to test it more thoroughly along the way.

Pavlin, one thing I accidentally noticed: in `computeExactGradient`, there is some logging into text files in the current master (https://github.com/KlugerLab/FIt-SNE/blob/master/src/tsne.cpp#L925), but it's absent in your branch (https://github.com/pavlin-policar/FIt-SNE/blob/refactor-interpolation/src/tsne.cpp#L859). Why is that? I only noticed because I was complaining about it the other day: https://github.com/KlugerLab/FIt-SNE/issues/26.

**Pull request merged**
