### PR TITLE
Timing fixes

### PR DESCRIPTION
**Pull request by dkobak**
Two tiny things:

(1) When using `-DTIME_CODE`, the time taken to compute the error was displayed before `Iteration %d (50 iterations in %.2f seconds)` which was confusing. I changed it.

(2) The report every 50 iterations was displayed after 51, 101, etc. iterations. I changed it so that now it's displayed after 50, 100, etc. :-)

### CODE REVIEW

**Comment by dkobak** [comment]
There was a very important problem in the Python wrapper: when the input array `X` contained 32-bit floats (or something else, but not doubles), then the whole thing was producing very weird and very puzzling outputs. Took me some time to figure out what was going on! So now I convert everything to doubles in the `fast_tsne.py`.

**Comment by dkobak** [comment]
One more tiny thing: I moved
```
    if (nthreads == 0) {
        nthreads = std::thread::hardware_concurrency();
    }
```
from `run()` to `main()` before
```
std::cout<<"fast_tsne nthreads: "<< nthreads <<std::endl;
```
so that the output is meaningful (not 0) if `nthreads` is not passed in.

**Comment by linqiaozhi** [comment]
Great changes, thanks so much @dkobak!

I had an unrelated question about `fast_tsne.py`. In the README.md, the default compile line outputs the binary into the `bin/` folder, and then `fast_tsne.R` and `fast_tsne.m,` can be run from the the root of the repository as they have `bin/fast_tsne` hardcoded.  In contrast, the `fast_tsne.py` looks for the `fast_tsne` binary in the current directory. So, it seems like the user either needs to modify the compile line in the README or copy the resulting binary to the root of the directory. 

Would it make sense to change that so that it's consistent with the default compile line (i.e. to change [this](https://github.com/KlugerLab/FIt-SNE/blob/master/fast_tsne.py#L86) line to `subprocess.call(os.getcwd()+'/bin/fast_tsne')`)? Or am I missing something? I know you use that wrapper all the time...what do you think makes the most sense?

**Comment by linqiaozhi** [comment]
Yeah, I agree that none of the solutions are really perfectly optimal.

With `fast_tsne.R` all of my scripts do the following:

```
setwd(<FIt-SNE folder>)
source('fast_tsne.R')
```
Then everything runs. In MATLAB, it is similar, each script has the following:

```
cd <FIt-SNE folder>
```

So, it's not ideal, but at least there is no need to move files around. I kind of inherited this practice from the original BH t-SNE MATLAB wrapper...this is how it was done there. Note that the R wrapper does let the user pass in the location of the executable and the location of the temp files (which now that you mention it, probably breaks the `load_affinities` functionality, because the current folder does not have a `temp` folder), but I find it more convenient to just change directory temporarily. 

For a wrapper that is not a package (like on [pypi](https://pypi.org/project/fitsne/) or Pavlin's package), I'm not sure if there is a better way. What do you think?

**Comment by dkobak** [comment]
I see. Just a short question to make sure I understand correctly: when there is
```
fopen("temp/col_P.dat", "w+b")
```
or when we use 
```
data_path = "temp/data.dat";
```
in the C++ code, these paths are relative to what? Let's say the binary is in `~/github/FIt-SNE/bin/` and the wrapper is in `~/github/FIt-SNE/` and `~/github/FIt-SNE/` is added to the Matlab path, and the actual analysis script is in `~/work/`

**Comment by dkobak** [comment]
I think in Matlab this https://www.mathworks.com/help/matlab/ref/which.html should work: in all three scenarios that I listed above `fast_tsne()` is in Matlab's search path so `which('fast_tsne')` should return the path to it and one can add `bin` to that. 

For R what you suggest should also work, I think it's a clever solution.

> That's why for the R package, when allowing the user to pass the path to the binary (and hence allowing the wrapper to be called from a different directory)

Still don't understand why we need this functionality (after the above changes).

**Comment by dkobak** [comment]
An alternative R method that should work with `source('path/to/FIt-SNE/fast_tsne.R')` without `chdir=T` seems to be this: https://stackoverflow.com/a/30306616

> `getSrcDirectory(function(x) {x})`

> This defines an anonymous function (that does nothing) inside the script, and then determines the source directory of that function, which is the directory where the script i

**Pull request merged**
