### PR TITLE
Modifications to allow for compilation under Windows using MS Visual Studio

### PR DESCRIPTION
**Pull request by jspidlen**
This now compiles on OSX using
g++ -std=c++11 -O3  src/sptree.cpp src/tsne.cpp src/nbodyfft.cpp  -o bin/fast_tsne -pthread -lfftw3 -lm
as well as under Windows by opening and rebuilding the provided solution with MS Visual Studio (tested MS Visual Studio 2015). I have not tested compilation under Linux, but I assume it should work just fine.

### CODE REVIEW

**Comment by linqiaozhi** [comment]
This is great--thanks so much for making this happen, Josef!  It was clearly a non-trivial task!

I am happy to merge these changes, but I was wondering if it would be possible to change the file structure slightly. Is it possible to put the newly added Windows-specific files that are currently in src into a subfolder of src? For example, perhaps we could have a folder called src/winlibs or src/win32libs or anything you think appropriate. Otherwise, I think it is confusing to people when they try to find the C++ code that actually computes t-SNE (as opposed to these many libraries necessary for it to compile on Windows).

Same thing for the FFTW folder. Could we make it clear that this is Windows-specific FFTW (maybe changing the folder name to win32fftw or something)? Just worried that OSX and Linux users will see it there and think that they don't have to install FFTW separately. 

Thanks again for doing this!

**Comment by jspidlen** [comment]
Thanks George, that makes total sense. I have moved all the Windows-specific libraries and source codes under src/winlib, and the windows specific fftw under src/winlib/fftw. 

Compilation under OSX and Linux platforms is still the same g++ command. 

I have carefully hand-edited the MS Visual Studio solution and project XML files to reflect the changes. Compilation under Windows means opening and rebuilding the solution in Visual Studio.

**Comment by linqiaozhi** [comment]
Sorry for the delay! I wanted to find a way to run it on a Windows machine to try it out myself, and it seems to work!

Two questions:

I had to add the FFTW folder to the PATH for it to find the DLL when running the executable. Is that a required step? If so, perhaps we should add it to the readme? Or is there a better solution I am missing?

Also, I think we need to copy the FItSNE.exe to bin/fast_tsne for the R, Matlab, and Python wrappers to work with the current default settings. Is that also correct?

Anyways, sorry to keep bothering you with this! I just want to make sure I am not missing something, as I don't do any Windows development.

**Comment by jspidlen** [comment]
Thanks George,
good call! Yes, the FFTW DLLs need to be on your path in order to run
FItSNE.exe
on Windows. I have added a note about that to the README file. I think the
easiest way is to simply put the DLLs in the same folder with the .exe and
then it will just work (based on my experience). I also do most of my work
on OSX and Linux, and don't have much experience with Windows, but I
believe that generally, one could register DLLs under Windows and then
Windows should know where they are and load those as necessary. But I was
experimenting with it a bit and it does not seem to be the case for FFTW
DLLs since they don't seem to implement the DllRegisterServer entry point.
So I would just stick with the "put it in the same folder" approach.

You currently don't have any binaries in the bin folder and so users are
required to compile it themselves before they can use it. So I didn't
add FItSNE.exe
either. The compilation may not be that trivial for some of them, so one
could add all the binaries (and the DLLs) to the bin folder to make their
life easier. The downside is that one would need to keep it in sync (i.e.,
recompile on all platforms every time there is a change in the source
code)... Thoughts?

As far as the wrappers go, I was only using the R wrapper and there, you
had the fast_tsne_path parameter of the wrapping function, so one can just
pass on a path to the .exe and it all works. I have tried to add a better
(platform-specific) default value for that as well. With the MATLAB and
Python wrappers, it seems that you may have hard-coded the path to some
extent, so this could be improved, but my MATLAB and Python skills are not
that great (and I don't currently have either of those installed on the
machines that I am working on). So if this is critical, it would be
preferable if someone more experienced could fix that :-)

Best,
Josef

**Comment by linqiaozhi** [comment]
Thanks so much for your help, Josef! I just merged it! Please let me know if my changes to the README are okay.

You're right--we should think about whether it would be good to distribute a binary version of FIt-SNE instead of requiring users to compile it. Honestly, I think that the ideal thing would be to actually have an R package on CRAN like how we have a PyPI package, and to make them platform independent, this way users wouldn't have to come to github at all...but that is future work.

**Comment by dkobak** [comment]
@jspidlen @linqiaozhi What would be needed to include `FIt-SNE.exe` into this package?

I think Linux users are expected to be fine with compiling the code from source, especially because it's just copy-paste of 1 line of code into the terminal. So I don't think one needs to include Linux binaries. However, I am not sure compilation is so easy for Windows users. I am sure that many Windows users won't even have MS Studio available. So I would strongly suggested to have `FIt-SNE.exe` that one could download and simply use as is.

Can one of you do it? I am not very familiar with Windows ecosystem; would one also need to provide some additional DLLs that it runs out of the box?

**Comment by jspidlen** [comment]
The required DLLs to compile and run on Windows should be all in here. I suppose we could include the FIt-SNE.exe, but the version that I have is obsolete by now (several fixes and significant speed improvements since I have last compiled it under Windows) and I do not regularly use Windows, so it would require some effort to setup a Windows box and recompile... but the main issue is, even if I did it now, it will get obsolete / out of sync over time. @linqiaozhi thoughts? If you think I should do it, I'll find a way...

**Comment by linqiaozhi** [comment]
@dkobak Thanks for the suggestion. I agree that it is a lot to ask Windows users to download MS Studio and compile. At least for OS X and Linux the tools are more or less built in, but that is not the case for Windows.

@jspidlen raises a great point, though. With each commit, we would have to recompile the binary which is a bit inconvenient. While I don't use Windows, I have set up a Windows VM that I use to test the software--so I could probably use that to maintain the binary. That being said, I think we first need to have a "release" system set up for this to make sense. Then it is easy for the user to know which version of the binary they have and to what code it corresponds to.  I've mentioned this before to Dmitry [here](https://github.com/KlugerLab/FIt-SNE/pull/52#issuecomment-430216361).

Github has a system for managing releases that we could easily use (for example, see Seurat [here](https://github.com/satijalab/seurat/releases)), and we could follow [Semantic versioning](https://semver.org/), starting with v1.0.0. And we can have the binary output "Running FIt-SNE vX.Y.Z", so that users are aware of which version they are using. 

What do you guys think of that? I am open to suggestions.

**Comment by jspidlen** [comment]
1) Releases and semantic versioning would be a great idea. I'd also suggest
that the binary be modified so that it prints out its version on stdout
when run without any arguments (or with --version or something).
2) We have recently discovered that some of our other software on Windows
runs close to 30% faster when compiled using MinGW/GCC as opposed to MS
Visual Studio; it appears to be mostly related to heavy use of templated
classes, which MS Visual Studio doesn't seem to handle all that well. So I
suspect that FIt-SNE may bot be affected that much, but it would be worth
checking should you be distributing binary releases.

**Comment by dkobak** [comment]
@linqiaozhi I don't mind versioning. As I said, I have little experience with this, but it sounds as a good idea. I would perhaps go over all the wrappers once more to check for consistency in parameter names (e.g. `stop_lying_iter` that was recently changed in Python), because AFAIK semantic versioning would require to change the version number whenever one changes anything that is not back-compatible. So before releasing 1.0.0 it makes sense to unify things like that.

I think that releasing an .exe file is pretty important even if it lags a bit behind the current version (i.e. not always updated with every commit). I am worried that some people who want to try FIt-SNE would not be able to do it currently. So I'd make this a priority. Shall I start a new issue on that?

**Comment by dkobak** [comment]
@jspidlen Apologies for off-topic, but I just realized that you are a co-author on https://www.biorxiv.org/content/early/2018/10/24/451690 which I read earlier today. Nice stuff! I sent Anna lots of comments already. Running BH t-SNE on the 20 mln dataset must have been such a pain! :)

PS. George, you should take a look at that preprint too.

**Comment by linqiaozhi** [comment]
@jspidlen @dkobak I implemented the versioning (version 1.0.0 is out!), the version number is output when the binary is run, and also linked to a binary which I included as part of the release. Please take a look and let me know if it looks all right. If you get your hands on a Windows computer at some point it would be great to try the binary out on a different machine (but from our previous discussion I don't think you do, so no problem).

**Pull request merged**
